# -*- coding: utf-8 -*-
"""hr_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3djaMr-KbFuSIKB5SutfUkickX0ci99
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('hr_attrition_data.csv')
df.head()

total_employees = len(df)
attrition_count = df[df['Attrition'] == 'Yes'].shape[0]
attrition_rate = (attrition_count / total_employees) * 100

print(f"Total Employees: {total_employees}")
print(f"Attrition Count: {attrition_count}")
print(f"Attrition Rate: {attrition_rate:.2f}%")

dept_attrition = df.groupby('Department')['Attrition'].apply(
    lambda x: (x == 'Yes').sum() / len(x) * 100
).sort_values(ascending=False)
print(dept_attrition)

overtime_attrition = df.groupby('OverTime')['Attrition'].apply(
    lambda x: (x == 'Yes').sum() / len(x) * 100
).sort_values(ascending=False)
print(overtime_attrition)

role_attrition = df.groupby('JobRole')['Attrition'].apply(
    lambda x: (x == 'Yes').sum() / len(x) * 100
).sort_values(ascending=False)
print(role_attrition)

marital_attrition = df.groupby('MaritalStatus')['Attrition'].apply(
    lambda x: (x == 'Yes').sum() / len(x) * 100
).sort_values(ascending=False)
print(marital_attrition)

travel_attrition = df.groupby('BusinessTravel')['Attrition'].apply(
    lambda x: (x == 'Yes').sum() / len(x) * 100
).sort_values(ascending=False)
print(travel_attrition)

df['Attrition_Flag'] = df['Attrition'].map({'Yes': 1, 'No': 0})

numeric_cols = ['Age', 'MonthlyIncome', 'DistanceFromHome', 'YearsAtCompany',
                 'JobSatisfaction', 'WorkLifeBalance', 'EnvironmentSatisfaction',
                 'TotalWorkingYears', 'YearsSinceLastPromotion']

correlation = df[numeric_cols + ['Attrition_Flag']].corr()['Attrition_Flag'].sort_values()
print(correlation)

comparison = df.groupby('Attrition')[['MonthlyIncome', 'YearsAtCompany', 'Age', 'TotalWorkingYears']].mean()
print(comparison)

plt.figure(figsize=(8,6))
correlation.drop('Attrition_Flag').plot(kind='barh', color='steelblue')
plt.title('Correlation of Factors with Attrition')
plt.xlabel('Correlation Coefficient')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
dept_attrition.plot(kind='bar', color='coral')
plt.title('Attrition Rate % by Department')
plt.ylabel('Attrition Rate (%)')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()